Class Project-Phase III/flight-ticket-booksystem/FlightTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from booksystem import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^booksystem/admin/finance', views.admin_finance, name='admin_finance'),
    url(r'^booksystem/', include('booksystem.urls')),
    url(r'', include('booksystem.urls')),
]

Class Project-Phase III/flight-ticket-booksystem/booksystem/urls.py
from django.conf.urls import url
from . import views

app_name = 'booksystem'  # Add this property to facilitate Jinja syntax

urlpatterns = [
    # Registration and Login
    url(r'^register/$', views.register, name='register'),  # registered
    url(r'^login_user/$', views.login_user, name='login_user'),  # Log in to
    url(r'^logout_user/$', views.logout_user, name='logout_user'),  # logout

    # The main page
    url(r'^$', views.index, name='index'),  # The welcome page
    url(r'^result/$', views.result, name='result'),  # The search results
    url(r'^user_info/$', views.user_info, name='user_info'),  # The user information
    url(r'^book/flight/(?P<flight_id>[0-9]+)/$', views.book_ticket, name='book_ticket'),  # booking
    url(r'^refund/flight/(?P<flight_id>[0-9]+)/$', views.refund_ticket, name='refund_ticket'),  # refund
]

Class Project-Phase III/flight-ticket-booksystem/booksystem/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


# Create your models here.
# Adding primary_key overrides the default primary key
class Flight(models.Model):
    user = models.ManyToManyField(User, default=1)
    name = models.CharField(max_length=100)
    leave_city = models.CharField(max_length=100, null=True)
    arrive_city = models.CharField(max_length=100, null=True)
    leave_airport = models.CharField(max_length=100, null=True)
    arrive_airport = models.CharField(max_length=100, null=True)
    leave_time = models.DateTimeField(null=True)
    arrive_time = models.DateTimeField(null=True)
    capacity = models.IntegerField(default=0, null=True)
    price = models.FloatField(default=0, null=True)
    book_sum = models.IntegerField(default=0, null=True)


class Country(models.Model)
    def __str__(self):
        return self.name

Class Project-Phase III/flight-ticket-booksystem/booksystem/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Flight


class PassengerInfoForm(forms.Form):
    leave_city = forms.CharField(label='leave_city', max_length=100)
    arrive_city = forms.CharField(label='arrive_city', max_length=100)
    leave_date = forms.DateField(label='leave_date')


# Customize input information for the Flight object
class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        exclude = ['user']  # User information cannot be entered from the background


# Fields that the user needs to enter
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Class Project-Phase III/flight-ticket-booksystem/booksystem/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from .forms import PassengerInfoForm, UserForm
from .models import Flight
from .classes import IncomeMetric, Order
from django.contrib.auth.models import Permission, User
import datetime, pytz
from operator import attrgetter

ADMIN_ID = 1


def admin_finance(request):
    all_flights = Flight.objects.all()
    all_flights = sorted(all_flights, key=attrgetter('leave_time'))

    # Tag the input for each day of the flight with a different time [week, month, day]
    week_day_incomes = []
    month_day_incomes = []
    year_day_incomes = []

    # Use SET to store all weeks, months, and years
    week_set = set()
    month_set = set()
    year_set = set()
    for flight in all_flights:
        if flight.income > 0:  # Only revenue-generating flights are counted
            # Tag Last Week
            this_week = flight.leave_time.strftime('%W')  # datetime获取周
            week_day_incomes.append((this_week, flight.income))  # Add a tuple (Week, Income)
            week_set.add(this_week)

            this_month = flight.leave_time.strftime('%m')  # Datetime for month
            month_day_incomes.append((this_month, flight.income))  # Add a tuple (month, income)
            month_set.add(this_month)

            this_year = flight.leave_time.strftime('%Y')  # Datetime for years
            year_day_incomes.append((this_year, flight.income))  # Add a tuple (year, income)
            year_set.add(this_year)


    # # Store weekly income in the Week_Incomes List with Incomemetric type
    week_incomes = []
    for week in week_set:
        income = sum(x[1] for x in week_day_incomes if x[0] == week)  # The sum of income of the same week
        flight_sum = sum(1 for x in week_day_incomes if x[0] == week)  # Total number of flights in the same week
        week_income = IncomeMetric(week, flight_sum, income)  # Store the data in the Incomemetric class to facilitate Jinja syntax
        week_incomes.append(week_income)
    week_incomes = sorted(week_incomes, key=attrgetter('metric'))  # List Week_Incomes are arranged in ascending order weekly


    # Store the monthly income in the Month_Incomes List with IncomeMetric type
    month_incomes = []
    for month in month_set:
        income = sum(x[1] for x in month_day_incomes if x[0] == month)
        flight_sum = sum(1 for x in month_day_incomes if x[0] == month)
        month_income = IncomeMetric(month, flight_sum, income)
        month_incomes.append(month_income)
    month_incomes = sorted(month_incomes, key=attrgetter('metric'))  # 将List类型的 month_incomes 按月份升序排列


    # The annual income is stored in the Year_Incomes List with Incomemetric type
    year_incomes = []
    for year in year_set:
        income = sum(x[1] for x in year_day_incomes if x[0] == year)
        flight_sum = sum(1 for x in year_day_incomes if x[0] == year)
        year_income = IncomeMetric(year, flight_sum, income)
        year_incomes.append(year_income)
    year_incomes = sorted(year_incomes, key=attrgetter('metric'))  # Arrange the YEAR_INDS of the List type in ascending order of year


    passengers = User.objects.exclude(pk=1)  # Get rid of administrators
    order_set = set()
    for p in passengers:
        flights = Flight.objects.filter(user=p)
        for f in flights:
            route = f.leave_city + ' → ' + f.arrive_city
            order = Order(p.username, f.name, route, f.leave_time, f.price)
            order_set.add(order)


    context = {
        'week_incomes': week_incomes,
        'month_incomes': month_incomes,
        'year_incomes': year_incomes,
        'order_set': order_set
    }
    return context


def user_info(request):
    if request.user.is_authenticated():
        # If the user is an administrator, render company flight revenue statistics page admin_finance
        if request.user.id == ADMIN_ID:
            context = admin_finance(request)  # Gets the data to be passed to the front end
            return render(request, 'booksystem/admin_finance.html', context)
        # If the user is an ordinary user, the ticket information of the render user is user_info
        else:
            booked_flights = Flight.objects.filter(user=request.user)  # Filters the flight booked by the user from the booksystem_flight_user table
            context = {
                'booked_flights': booked_flights,
                'username': request.user.username,  # Navigation bar information updated
            }
            return render(request, 'booksystem/user_info.html', context)
    return render(request, 'booksystem/login.html')  # If the user is not logged in, the render login page



def index(request):
    return render(request, 'booksystem/index.html')


# csrf
@csrf_exempt
def book_ticket(request, flight_id):
    if not request.user.is_authenticated:  # Render logs in the page if not logged in
        return render(request, 'booksystem/login.html')
    else:
        flight = Flight.objects.get(pk=flight_id)
        booked_flights = Flight.objects.filter(user=request.user)  # Return QuerySet

        if flight in booked_flights:
            return render(request, 'booksystem/book_conflict.html')

        # After book_flight. HTML click to confirm, request is a POST method, passing no value, but a POST signal
        # Confirmed booking, Flight database changed

        # Verify that the same ticket can only be booked once
        if request.method == 'POST':
            if flight.capacity > 0:
                flight.book_sum += 1
                flight.capacity -= 1
                flight.income += flight.price
                flight.user.add(request.user)
                flight.save()
        # Pass the changed ticket information
        context = {
            'flight': flight,
            'username': request.user.username
        }
        return render(request, 'booksystem/book_flight.html', context)


# refund
def refund_ticket(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    flight.book_sum -= 1
    flight.capacity += 1
    flight.income -= flight.price
    flight.user.remove(request.user)
    flight.save()
    return HttpResponseRedirect('/booksystem/user_info')


# Log out
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'booksystem/login.html', context)


# The login
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        user = authenticate(username=username, password=password)
        if user is not None:  # Login successful
            if user.is_active:  # Load the booking page
                login(request, user)
                context = {
                    'username': request.user.username
                }
                if user.id == ADMIN_ID:
                    context = admin_finance(request)  # Gets the data to be passed to the front end
                    return render(request, 'booksystem/admin_finance.html', context)
                else:
                    return render(request, 'booksystem/result.html', context)
            else:
                return render(request, 'booksystem/login.html', {'error_message': 'Your account has been disabled'})
        else:  # Login failed
            return render(request, 'booksystem/login.html', {'error_message': 'Invalid login'})
    return render(request, 'booksystem/login.html')


# registered
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                context = {
                    'username': request.user.username
                }
                return render(request, 'booksystem/result.html', context)  # Successful registration goes directly to the Render Result page
    context = {
        "form": form,
    }
    return render(request, 'booksystem/register.html', context)


# Search results page
def result(request):
    if request.method == 'POST':
        form = PassengerInfoForm(request.POST)  # Bind data to the form
        if form.is_valid():
            passenger_lcity = form.cleaned_data.get('leave_city')
            passenger_acity = form.cleaned_data.get('arrive_city')
            passenger_ldate = form.cleaned_data.get('leave_date')
            # print(type(passenger_ldate))


            # china_tz = pytz.timezone('Asia/Shanghai')
            # passenger_ltime = datetime.datetime(
            #     year=passenger_ldate.year,
            #     month=passenger_ldate.month,
            #     day=passenger_ldate.day,
            #     hour=0, minute=0, second=0,
            #     tzinfo=china_tz
            # )


            passenger_ltime = datetime.datetime.combine(passenger_ldate, datetime.time())
            print(passenger_ltime)


            all_flights = Flight.objects.filter(leave_city=passenger_lcity, arrive_city=passenger_acity)
            usable_flights = []
            for flight in all_flights:  # off-set aware
                flight.leave_time = flight.leave_time.replace(tzinfo=None)
                if flight.leave_time.date() == passenger_ltime.date():
                    usable_flights.append(flight)

            # Sort by different keys
            usable_flights_by_ltime = sorted(usable_flights, key=attrgetter('leave_time'))  # The departure time is from morning till night

Class Project-Phase III/flight-ticket-booksystem/booksystem/templates/booksystem/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Management System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {#    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">#}
    {% block style %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body style="background-color: #f1f1f1">
<nav class="nav navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'booksystem:index' %}">CSU Airlines</a>
        </div>
        <!-- Items -->
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'booksystem:result' %}">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; ticket
                </a>
            </li>
            <li>
                <a href="{% url 'booksystem:user_info' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Personal center
                </a>
            </li>
            <li>
                {% block login_display %}
                    <a href="{% url 'booksystem:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; login
                    </a>
                {% endblock %}
            </li>
            <li>
                <a href="{% url 'booksystem:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; exit
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

Class Project-Phase III/flight-ticket-booksystem/booksystem/templates/booksystem/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Reservation System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% load static %}
    <style>
        body {
            /*background: url("../../static/img/flight-bg.jpg");*/
            background: url("{% static 'img/flight-bg.jpg' %}");
            background-size: cover;
        }
    </style>

</head>
<body>

<!--导航条适应背景色-->
<nav class="navbar nav-divider">
    <div class="container-fluid" style="margin-top: 10px">
        <div class="navbar-header">
            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 50px;">CSU Airlines</a>
        </div>
        <div class="navbar-right">
            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 24px;">LOG IN</a>
        </div>

    </div>
</nav>

<div class="container-fluid" style="position:absolute;margin-top:10%;width: 35%;left: 5%">
    <h1 style="color: white">Where are we flying now ?</h1>
    <br>
    <form class="form-horizontal" role="form" action="{% url 'booksystem:result' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="leave_city" class="input-group-addon">Departure city</label>   <!--Input must specify a name-->
            <input id="leave_city" type="text" name="leave_city" class="form-control" placeholder="City">
        </div>
        <br>
        <div class="input-group">
            <label for="arrive_city" class="input-group-addon">Reach the city</label>
            <input id="arrive_city" type="text" name="arrive_city" class="form-control" placeholder="City">
        </div>
        <br>
        <div class="input-group">
            <label for="leave_date" class="input-group-addon">Departure date</label>
            <input id="leave_date" type="date" name="leave_date" class="form-control" placeholder="Date">
        </div>
        <br>
        <center>
            <button type="submit" class="btn btn-success">Let's Go</button>
        </center>
    </form>
</div>

</body>
</html>

Class Project-Phase III/flight-ticket-booksystem/booksystem/templates/booksystem/login.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>Login account</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="{% url 'booksystem:login_user' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_username" maxlength="10" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_password" maxlength="10" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Don't have an account? <a href="{% url 'booksystem:register' %}">Click here</a> to register.
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Class Project-Phase III/flight-ticket-booksystem/booksystem/templates/booksystem/result.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">welcome {{ username }} Sir/Madam</a>
{% endblock %}

{#This section is loaded first in the head section of base.html#}
{% block style %}

    <style>

        .main {
            margin-left: 50px;
            margin-right: 50px;
        }

        .search_form {
            background-color: white;
            margin-top: 25px;
            height: 90px;
        }

        .search_head {
            background-color: #f1f1f1;
            margin-top: 10px;
            height: 30px;
            text-align: center;
            font-weight: bold;
        }

        .search_result_by_ltime {
            background-color: #f1f1f1;
            margin-top: 10px;
        }

        .search_result_by_price {
            background-color: #f1f1f1;
            margin-top: 10px;
        }

        .one_line {
            background-color: white;
            height: 90px;
            margin-top: 10px;
            text-align: center;
        }

        .ico_search_type {
            display: inline-block;
            width: 20px;
            height: 20px;
            background: url('http://pic.c-ctrip.com/flight/searchlist/icon_search_select.png') no-repeat;
        }

        .ico_search_lcity {
            background-position: 0 0;
        }

        .ico_search_acity {
            background-position: 0 -20px;
        }

        .ico_search_ldate {
            background-position: 0 -40px;
        }

        .my_input {
            position: absolute;
            width: 80%;
        }

        .btn-warning {
            background-color: #ffb000;
        }

        .flight_name {
            line-height: 90px;
            font-size: x-large;
            font-weight: bold;
        }


    </style>
{% endblock %}

{% block js %}
    <script>
        function search_by_ltime() {
            document.getElementById("result_by_ltime").style.display = "block";
            document.getElementById("result_by_atime").style.display = "none";
            document.getElementById("result_by_price").style.display = "none";
        }
        function search_by_atime() {
            document.getElementById("result_by_ltime").style.display = "none";
            document.getElementById("result_by_atime").style.display = "block";
            document.getElementById("result_by_price").style.display = "none";
        }
        function search_by_price() {
            document.getElementById("result_by_ltime").style.display = "none";
            document.getElementById("result_by_atime").style.display = "none";
            document.getElementById("result_by_price").style.display = "block";
        }
    </script>
{% endblock %}

{% block content %}

    <div class="main">

        <!--The search box-->
        <div class="search_form">
            <div class="col-sm-12" style="margin-top: 20px">
                <form action="{% url 'booksystem:result' %}" method="post">
                    {% csrf_token %}
                    <div class="col-sm-3"> {# In the parent div, specify width:100% to make it the same width #}
                        <span class="ico_search_type ico_search_lcity"></span><br>
                        <input class="my_input" type="text" id="leave_city" name="leave_city" placeholder="City"
                               value="{{ leave_city }}">
                    </div>
                    <div class="col-sm-3">
                        <span class="ico_search_type ico_search_acity"></span><br>
                        <input class="my_input" type="text" id="arrive_city" name="arrive_city" placeholder="City"
                               value="{{ arrive_city }}">
                    </div>
                    <div class="col-sm-3">
                        <span class="ico_search_type ico_search_ldate"></span><br>
                        <input class="my_input" type="date" id="leave_date" name="leave_date" placeholder="Date"
                               value="{{ leave_date }}">
                    </div>
                    <div class="col-sm-3">
                        <div style="position: absolute;margin-top: 10px;margin-left: 35%">
                            <input class="btn btn btn-info" name="research_btn" type="submit" value="重新搜索">
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!--Title line (indicating the four sorting methods)-->
        <div class="search_head" id="search_head" style="display: {{ dis_search_head }}">
            <div class="col-sm-12">
                <button class="col-sm-3 btn btn-primary"> flight information</button>
                <button class="col-sm-3 btn btn-success" onclick="search_by_ltime()">departure time</button>
                <button class="col-sm-3 btn btn-danger" onclick="search_by_atime()">arrive time</button>
                <button class="col-sm-3 btn btn-warning" onclick="search_by_price()">price</button>
            </div>
        </div>

        <!--If you don't find it-->
        <div class="alert" id="search_failure"
             style="margin-top: 20px; background-color:white;display: {{ dis_search_failure }}">
            <h1>Dear passenger</h1>
            <p style="margin-left: 50px">
                Sorry, we do not have this flight available at present, please try to choose another flight, wish you a pleasant journey!
            </p>
        </div>

        <!--Sort by price-->
        <div class="search_result_by_price" id="result_by_price">
            {% for flight in usable_flights_by_price %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="flight_name">{{ flight.name }}</p> {# A single center #}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# Multi-line center #}
                                <span style="font-size: xx-large">{{ flight.leave_time }}</span>
                                <br>
                                {{ flight.leave_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ flight.arrive_time }}</span>
                                <br>
                                {{ flight.arrive_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">full</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ flight.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ flight.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' flight.id %}"
                                   class="btn btn-sm btn-warning">booking</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!--Sort by take-off time-->
        <div class="search_result_by_ltime" id="result_by_ltime" style="display: none">
            {% for flight in usable_flights_by_ltime %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="flight_name">{{ flight.name }}</p> {# A single center#}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# Multi-line center #}
                                <span style="font-size: xx-large">{{ flight.leave_time }}</span>
                                <br>
                                {{ flight.leave_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ flight.arrive_time }}</span>
                                <br>
                                {{ flight.arrive_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">full</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ flight.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ flight.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' flight.id %}"
                                   class="btn btn-sm btn-warning">booking</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="search_result_by_atime" id="result_by_atime" style="display: none">
            {% for flight in usable_flights_by_atime %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="flight_name">{{ flight.name }}</p> {# A single center #}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# Multi-line center #}
                                <span style="font-size: xx-large">{{ flight.leave_time }}</span>
                                <br>
                                {{ flight.leave_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ flight.arrive_time }}</span>
                                <br>
                                {{ flight.arrive_airport }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">full</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ flight.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ flight.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' flight.id %}"
                                   class="btn btn-sm btn-warning">booking</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}